name: Test Workflow 2
on:
  pull_request:
    types: [opened, edited]
  workflow_dispatch:
jobs:
  var:
    runs-on: ubuntu-latest
    steps:
      - name: Run Command
        run: echo "Hello, this was me"
